# 50PH1A Color Palette

# Neutrals
neutrals = [
	"#FFFFFF", 
	"#FAFAFA",
	"#F3F4F6",
	"#D4D4D8",
	"#a3a3a3",
	"#737373",
	"#525252",
	"#262626",
	"#18181B",
	"#000000"
]

# Colors
[red]
light = "#ef4444"
medium = "#dc2626"
dark = "#b91c1c"

[yellow]
light = "#fbbf24"
medium = "#f59e0b"
dark = "#d97706"

[green]
light = "#34d399"
medium = "#10b981"
dark = "#059669"

[blue]
light = "#7dd3fc"
medium = "#38bdf8"
dark = "#0284c7"

[purple]
light = "#c084fc"
medium = "#a855f7"
dark = "#9333ea"

