name: Publish

on:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          # Personal access token
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./
